version: '2'
services:
  linuxmachine:
    container_name: linux-machinegun
    image: node:20-alpine
    working_dir: /app
    ports: 
      - 4000:4000
    volumes:
      - ./:/app
    stdin_open: true # Mantiene stdin aperto
    tty: true        # Alloca pseudo-TTY
    command: sh      # Shell interattiva
    restart: unless-stopped